### ISSUE TITLE
Make bucket cli command (s3) creates additional root bucket

### ISSUE THREAD

**Issue by volchnik** [sekka1/aws-cli-docker#12]
Hello
In my docker-compose.yml, I have:
```
...
  aws-cli:
      image: garland/aws-cli-docker
      environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=eu-west-1
      links:
      - s3-service
      - sqs-service
      command: >
        sh -c "aws --endpoint-url=http://s3-service:4569 s3 mb s3://bucket1 &&
        aws --endpoint-url=http://s3-service:4569 s3 mb s3://bucket2"
```

When I'm checking created buckets with:
`aws s3 ls s3://`
got:

> s3-service

and then 
`aws s3 ls s3://s3-service/`

> bucket1
> bucket2
